version: 2.1

orbs:
  python: circleci/python@1.5.0
  k8s: digitalocean/k8s@0.1.1
  gcp-gcr: circleci/gcp-gcr@0.7.1
  kubernetes: circleci/kubernetes@0.11.0
  digitalocean: digitalocean/cli@0.1.1
  semantic-release: proxyco/semantic-release@4.0.0
  docker: circleci/docker@2.1.1
  slack: circleci/slack@4.4.4

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  empty:
    resource_class: small
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo << pipeline.parameters.GHA_Meta >>

  # Build and push Docker image to Registry
  build-and-push:
    executor: docker/docker
    resource_class: medium
    parameters:
      tag:
        description: |
          Tag to use for image.
        type: string
      registry:
        description: |
          Registry to use for image.
        type: string
        default: registry.digitalocean.com
      image:
        description: |
          Image name.
        type: string
    environment:
      GIT_TOKEN: TOKEN
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11

      - checkout
      - run: echo << pipeline.parameters.GHA_Meta >>
      - attach_workspace:
          at: /home/circleci/project

      - digitalocean/install
      - digitalocean/initialize:
          digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
      - run: doctl registry login

      - docker/build:
          image: << parameters.image >>
          registry: << parameters.registry >>
          tag: << pipeline.parameters.GHA_Meta >>
          dockerfile: docker/production.Dockerfile
          use-buildkit: true
          # this is not usefull when building small images -> maybe we get a performace increase if the build image is bigger (doc2api?)
          cache_from: "<< parameters.registry >>/<< parameters.image >>:latest"
          extra_build_args: "--build-arg BUILDKIT_INLINE_CACHE=1"
      - run: docker tag << parameters.registry >>/<< parameters.image >>:<< pipeline.parameters.GHA_Meta >> << parameters.registry >>/<< parameters.image >>:<< pipeline.git.branch >>-latest

      - docker/push:
          image: << parameters.image >>
          registry: << parameters.registry >>
          tag: << pipeline.parameters.GHA_Meta >>
      - docker/push:
          image: << parameters.image >>
          registry: << parameters.registry >>
          tag: << pipeline.git.branch >>-latest

  # Create/Update Digitalocean Deployment
  deploy:
    executor:
      name: gcp-gcr/default
    resource_class: small
    parameters:
      branch:
        description: |
          Git branch -> important for k8s file
        type: string
      tag:
        description: |
          Tag to use for image.
        type: string
      cluster-name:
        description: |
          Name of the GKE cluster
        type: string
      namespace:
        description: |
          The deployment namespace.
        type: string
        default: ""
      deployment:
        description: |
          Deployment name.
        type: string
      container:
        description: |
          The deployment container including the registry and path.
        type: string

    steps:
      - checkout

      - kubernetes/install-kubectl
      - digitalocean/install
      - digitalocean/initialize:
          digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
      - run: doctl kubernetes cluster kubeconfig save << parameters.cluster-name >>

      # kubectl patch deployment deployment-name -n namespace --patch '{"spec":{"template":{"spec":{"containers":[{"name":"deployment-name", "image": "registry:tag"}]}}}}'
      - run: |

          kubectl patch deployment << parameters.deployment >> -n << parameters.namespace >> \
            --patch '{"spec":{"template":{"spec":{"containers":[{"name":"<< parameters.deployment >>", "image": "<< parameters.container >>:<< pipeline.parameters.GHA_Meta >>"}]}}}}'

          kubectl rollout restart deployment << parameters.deployment >> -n << parameters.namespace >>

  deploy_terraform:
    executor: gcp-gcr/default
    resource_class: small
    parameters:
      tag:
        description: Tag to use for image.
        type: string
      api-key:
        description: api-key
        type: string

    steps:
      - run: |
          curl -X 'POST' \
            'https://<<pipeline.git.branch >>.terraform.cloudintegration.eu/version/update_docker_version?registry=insight&version=<< pipeline.parameters.GHA_Meta >>' \
            -H 'accept: application/json' \
            -H 'X-API-KEY: << parameters.api-key >>' \
            -d ''
          sleep 5
          curl -X 'GET' \
            'https://<<pipeline.git.branch >>.terraform.cloudintegration.eu/webhook/insight/refresh' \
            -H 'accept: application/json' \
            -H 'X-API-KEY: << parameters.api-key >>' \
            -d ''

  deploy_terraform_prod:
    executor: gcp-gcr/default
    parameters:
      tag:
        description: Tag to use for image.
        type: string
      api-key:
        description: api-key
        type: string

    steps:
      - run: |
          curl -X 'POST' \
            'https://terraform.cloudintegration.eu/version/update_docker_version?registry=insight&version=<< pipeline.parameters.GHA_Meta >>' \
            -H 'accept: application/json' \
            -H 'X-API-KEY: << parameters.api-key >>' \
            -d ''
          curl -X 'GET' \
            'https://terraform.cloudintegration.eu/webhook/insight/refresh' \
            -H 'accept: application/json' \
            -H 'X-API-KEY: << parameters.api-key >>' \
            -d ''

workflows:
  version: 2
  display:
    jobs:
      - empty
  deployment_workflow_dev:
    when:
      and:
        - equal: ["dev", << pipeline.git.branch >>]
        - equal: ["CircleCI", << pipeline.parameters.GHA_Action >>]
    jobs:
      # Build and push Docker image to Digitalocean Registry
      - build-and-push:
          context:
            - Digitalocean
            - GitHub
          tag: << pipeline.parameters.GHA_Meta >>
          image: cloudintegration/tooljet

      - deploy:
          branch: << pipeline.git.branch >>
          namespace: tooljet-dev
          deployment: tooljet-dev
          tag: << pipeline.parameters.GHA_Meta >>
          container: registry.digitalocean.com/cloudintegration/tooljet
          cluster-name: k8s-1-21-2-do-1-fra1-1625240177379
          requires:
            - build-and-push

      - deploy_terraform:
          tag: << pipeline.parameters.GHA_Meta >>
          api-key: 8atbbjpdZJTR7s669S7si851bFayy5MhdNE21T2wqazvZhz8MBm6vzQGdxpeuLAIvgqncf1UZ6X51n31QnZprQdC5weJTv102lRSqM2iv5TZ9Pkihm3iVc9B12lZknaq
          requires:
            - build-and-push

  deployment_workflow_stage:
    when:
      and:
        - equal: ["stage", << pipeline.git.branch >>]
        - equal: ["CircleCI", << pipeline.parameters.GHA_Action >>]
    jobs:
      # Build and push Docker image to Digitalocean Registry
      - build-and-push:
          context:
            - Digitalocean
            - GitHub
          tag: << pipeline.parameters.GHA_Meta >>
          image: cloudintegration/tooljet

      - deploy:
          branch: << pipeline.git.branch >>
          namespace: tooljet-dev
          deployment: tooljet-dev
          tag: << pipeline.parameters.GHA_Meta >>
          container: registry.digitalocean.com/cloudintegration/tooljet
          cluster-name: k8s-1-21-2-do-1-fra1-1625240177379
          requires:
            - build-and-push

      - deploy_terraform:
          tag: << pipeline.parameters.GHA_Meta >>
          api-key: UMkgUNzDoZNmlWBEBOELOGtEmd5w66UleOZIUM9JfGrM4OeAH3dDkhO1BwJhYeJ9SDMV7Ul94P4eRSK3uk4DWr42ly7aVehbwwOm6Mu0hVHzI0utlaQZqpKtLS0hBGop
          requires:
            - build-and-push

  deployment_workflow_sandbox:
    when:
      and:
        - equal: ["sandbox", << pipeline.git.branch >>]
        - equal: ["CircleCI", << pipeline.parameters.GHA_Action >>]
    jobs:
      # Build and push Docker image to Digitalocean Registry
      - build-and-push:
          context:
            - Digitalocean
            - GitHub
          tag: << pipeline.parameters.GHA_Meta >>
          image: cloudintegration/tooljet

      - deploy:
          branch: << pipeline.git.branch >>
          namespace: tooljet-dev
          deployment: tooljet-dev
          tag: << pipeline.parameters.GHA_Meta >>
          container: registry.digitalocean.com/cloudintegration/tooljet
          cluster-name: k8s-1-21-2-do-1-fra1-1625240177379
          requires:
            - build-and-push

      - deploy_terraform:
          tag: << pipeline.parameters.GHA_Meta >>
          api-key: 26CuVBsJUTfSP20KdR5jwHbOCaEHHdMzR1ZUPHHtf8voY8nXee4uh1Hr64cKIx2yBQ6mnrTNaxZXsvwLPyJTubbRm31O6kyvrShApSMrxJSl0U6XSFKlrLVA1tur7ALq
          requires:
            - build-and-push

  deployment_workflow_prod:
    when:
      and:
        - equal: ["prod", << pipeline.git.branch >>]
        - equal: ["CircleCI", << pipeline.parameters.GHA_Action >>]
    jobs:
      # Build and push Docker image to Digitalocean Registry
      - build-and-push:
          context:
            - Digitalocean
            - GitHub
          tag: << pipeline.parameters.GHA_Meta >>
          image: cloudintegration/tooljet

      - deploy:
          branch: << pipeline.git.branch >>
          namespace: tooljet-dev
          deployment: tooljet-dev
          tag: << pipeline.parameters.GHA_Meta >>
          container: registry.digitalocean.com/cloudintegration/tooljet
          cluster-name: k8s-1-21-2-do-1-fra1-1625240177379
          requires:
            - build-and-push

      - deploy_terraform_prod:
          tag: << pipeline.parameters.GHA_Meta >>
          api-key: 26CuVBsJUTfSP20KdR5jwHbOCaEHHdMzR1ZUPHHtf8voY8nXee4uh1Hr64cKIx2yBQ6mnrTNaxZXsvwLPyJTubbRm31O6kyvrShApSMrxJSl0U6XSFKlrLVA1tur7ALq
          requires:
            - build-and-push
