version: 2.1

orbs:
  python: circleci/python@1.5.0
  k8s: digitalocean/k8s@0.1.1
  gcp-gcr: circleci/gcp-gcr@0.7.1
  kubernetes: circleci/kubernetes@0.11.0
  digitalocean: digitalocean/cli@0.1.1
  semantic-release: proxyco/semantic-release@4.0.0
  docker: circleci/docker@2.1.1
  slack: circleci/slack@4.4.4

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  empty:
    resource_class: small
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo << pipeline.parameters.GHA_Meta >>

  # Build and push Docker image to Registry
  build-and-push:
    executor: docker/docker
    resource_class: medium
    parameters:
      tag:
        description: |
          Tag to use for image.
        type: string
      registry:
        description: |
          Registry to use for image.
        type: string
        default: registry.digitalocean.com
      image:
        description: |
          Image name.
        type: string
    environment:
      GIT_TOKEN: TOKEN
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11

      - checkout
      - run: echo << pipeline.parameters.GHA_Meta >>
      - attach_workspace:
          at: /home/circleci/project

      - digitalocean/install
      - digitalocean/initialize:
          digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
      - run: doctl registry login

      - docker/build:
          image: << parameters.image >>
          registry: << parameters.registry >>
          tag: << pipeline.parameters.GHA_Meta >>
          dockerfile: docker/production.Dockerfile
          use-buildkit: true
          # this is not usefull when building small images -> maybe we get a performace increase if the build image is bigger (doc2api?)
          cache_from: "<< parameters.registry >>/<< parameters.image >>:latest"
          extra_build_args: "--build-arg BUILDKIT_INLINE_CACHE=1"
      - run: docker tag << parameters.registry >>/<< parameters.image >>:<< pipeline.parameters.GHA_Meta >> << parameters.registry >>/<< parameters.image >>:<< pipeline.git.branch >>-latest

      - docker/push:
          image: << parameters.image >>
          registry: << parameters.registry >>
          tag: << pipeline.parameters.GHA_Meta >>
      - docker/push:
          image: << parameters.image >>
          registry: << parameters.registry >>
          tag: << pipeline.git.branch >>-latest

  deploy:
    executor: gcp-gcr/default
    resource_class: small
    parameters:
      branch:
        description: |
          Git branch -> important for k8s file
        type: string
      tag:
        description: |
          Tag to use for image.
        type: string
      cluster-name:
        description: |
          Name of the GKE cluster
        type: string
      namespace:
        description: |
          The deployment namespace.
        type: string
        default: ""
      deployment:
        description: Deployment name.
        type: string
      deployment_celery:
        description: Celery deployment name.
        type: string
      container:
        description: |
          The deployment container including the registry and path.
        type: string
      - kubernetes/install-kubectl
      - digitalocean/install
      - digitalocean/initialize:
          digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
      - run: doctl kubernetes cluster kubeconfig save << parameters.cluster-name >>

# kubectl patch deployment deployment-name -n namespace --patch '{"spec":{"template":{"spec":{"containers":[{"name":"deployment-name", "image": "registry:tag"}]}}}}'
      - run: |
      
          kubectl patch deployment << parameters.deployment >> -n << parameters.namespace >> \
            --patch '{"spec":{"template":{"spec":{"containers":[{"name":"<< parameters.deployment >>", "image": "<< parameters.container >>:<< pipeline.parameters.GHA_Meta >>"}]}}}}'



workflows:
  version: 2
  display:
    jobs:
      - empty
  deployment_workflow:
    when:
      and:
        - or:
            - equal: ["dev", << pipeline.git.branch >>]
            - equal: ["stage", << pipeline.git.branch >>]
            - equal: ["sandbox", << pipeline.git.branch >>]
            - equal: ["prod", << pipeline.git.branch >>]
        - equal: ["CircleCI", << pipeline.parameters.GHA_Action >>]
    jobs:
      # Build and push Docker image to Digitalocean Registry
      - build-and-push:
          context:
            - Digitalocean
            - GitHub
          tag: << pipeline.parameters.GHA_Meta >>
          image: cloudintegration/tooljet

      - deploy:
          branch: << pipeline.git.branch >>
          namespace: tooljet-dev
          deployment: tooljet-dev
          tag: << pipeline.parameters.GHA_Meta >>
          context: Digitalocean
          container: registry.digitalocean.com/cloudintegration/tooljet
          cluster-name: k8s-1-21-2-do-1-fra1-1625240177379
          requires:
            - build-and-push
